apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: springapp
        image: IMAGEID
        ports:
        - containerPort: 8080
